# Generated by Django 4.2.1 on 2023-07-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='number',
        ),
    ]
