# Generated by Django 4.2.1 on 2023-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sender_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
