# Generated by Django 4.2.1 on 2023-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField()),
                ('sender_address', models.TextField()),
                ('sender_number', models.IntegerField()),
                ('receiver_name', models.TextField()),
                ('receiver_address', models.TextField()),
                ('receiver_number', models.IntegerField()),
                ('item', models.TextField()),
                ('weight', models.IntegerField()),
                ('comment', models.TextField()),
                ('status', models.TextField()),
                ('pickup_time', models.TimeField(auto_now=True, verbose_name='last login')),
                ('pickup_date', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('destination', models.TextField()),
                ('peparted_time', models.TimeField(auto_now=True, verbose_name='last login')),
                ('mode', models.TextField()),
                ('freight', models.TextField()),
                ('booking_mode', models.TextField()),
                ('qnty', models.TextField()),
                ('invoice_no', models.TextField()),
                ('consignment', models.TextField()),
                ('consignment_no', models.TextField()),
            ],
        ),
    ]
