# Generated by Django 4.2.1 on 2023-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_items_comment_remove_items_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='status',
        ),
        migrations.AlterField(
            model_name='items',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
