# Generated by Django 4.2.1 on 2023-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_items_status_alter_items_pickup_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('message', models.TextField()),
                ('email', models.TextField()),
                ('time', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
        ),
    ]
