# Generated by Django 4.2.1 on 2023-07-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
